[project]
name = "liaoxuefeng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chardet>=5.2.0",
    "pillow>=12.0.0",
    "psutil>=7.1.3",
    "requests>=2.32.5",
]
